# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2cf4f16e0e2b8335af7bcfd1332199c8fc694c46b0508a2f8fc30661a48f2df05de700fc133bfebec9e23544a157ba0f22ac5bf930d3954a7ab76ba51ddf4364

test:
  secret_key_base: 58acd3fcb70c0687e5162610683aabede4141b3c7418e4a56e2a403883c314e8bfb5d6a348c158097a6785dff5abf528f9c3e3478893f50189b9cac32088695f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
